[skip ci] Begynnt å lage testklasse
navikt/pale-2-regler pull request #25
Opened 2023-01-17 12:43 UTC by oysbak

2023-02-06 12:38 UTC, andreasDev commented on build.gradle.kts
> +    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
Trenger vi denne? ser den er på versjon 5.8.1, de andre junit er på 5.9.1

2023-02-06 12:41 UTC, andreasDev commented on src/test/kotlin/no/nav/syfo/client/LegeSuspensjonClientTest.kt
> +//        )
Disse utkommenterte kodene kan fjernes

2023-02-06 12:42 UTC, andreasDev commented on src/test/kotlin/no/nav/syfo/client/LegeSuspensjonClientTest.kt
> +        assertEquals(true, true)
Denne vil alltid være equal, ser at den over er kommentert ut, det burde den ikke

2023-02-06 12:49 UTC, andreasDev requested changes
Legg gjerne til tester for disse reglene i RuleServiceTest også

BEHANDLER_MANGLER_AUTORISASJON_I_HPR
BEHANDLER_IKKE_LE_KI_MT_TL_FT_PS_I_HPR
BEHANDLER_SUSPENDERT
UGYLDIG_ORGNR_LENGDE
AVSENDER_FNR_ER_SAMME_SOM_PASIENT_FNR

det er bare disse som mangler

2023-02-06 14:16 UTC, MikAoJk commented on src/test/kotlin/no/nav/syfo/services/RuleServiceTest.kt
> +        assertEquals("PASIENT_YNGRE_ENN_13", validationResult.ruleHits[0].ruleName)
```suggestion
        runBlocking {
            val validationResult = ruleService.executeRuleChains(receivedLegeerklaering)       
            assertEquals("PASIENT_YNGRE_ENN_13", validationResult.ruleHits[0].ruleName)
        }
```

2023-02-06 14:17 UTC, MikAoJk commented on src/test/kotlin/no/nav/syfo/services/RuleServiceTest.kt
> +    fun `Test med utfyllt foedselsdato og pasient under 13 aar`() {
```suggestion
    fun `Utfyllt foedselsdato og pasient under 13 aar, regel truffet PASIENT_YNGRE_ENN_13`() {
```

2023-02-07 08:04 UTC, oysbak commented on build.gradle.kts
> +    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")
Fjernet linjen

2023-02-07 08:07 UTC, oysbak commented on src/test/kotlin/no/nav/syfo/client/LegeSuspensjonClientTest.kt
> +//        )
Fjernet

2023-02-07 08:13 UTC, oysbak commented on src/test/kotlin/no/nav/syfo/client/LegeSuspensjonClientTest.kt
> +        assertEquals(true, true)
Ryddet opp

2023-02-07 08:20 UTC, oysbak commented on src/test/kotlin/no/nav/syfo/services/RuleServiceTest.kt
> +        assertEquals("PASIENT_YNGRE_ENN_13", validationResult.ruleHits[0].ruleName)
Utført

2023-02-07 08:22 UTC, oysbak commented on src/test/kotlin/no/nav/syfo/services/RuleServiceTest.kt
> +    fun `Test med utfyllt foedselsdato og pasient under 13 aar`() {
Utført

2023-02-13 06:59 UTC, MikAoJk approved these changes

2023-02-13 08:39 UTC, merged